#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

ha2thz = 6579.68974479

with open('anaddb.out_PHFRQ','r') as fid:
    while True:
        tmp = fid.readline().strip().split()
        try:
            if tmp[1] == 'number_of_phonon_modes':
                nband = int(tmp[2])
                break
        except:
            continue


frq = np.loadtxt('anaddb.out_PHFRQ')*ha2thz

### creat a figure, set its size
fig, ax = plt.subplots()
fig.set_size_inches(8,6,forward=True)
fig.tight_layout(pad=3)


for i in range(nband):
    plt.plot(frq[:,i+1],marker='o',ms=0.0,mfc='w',mew=0.0,mec='k',lw='1.5',color='k')

# configure the plot
for axis in ['top','bottom','left','right']:
  ax.spines[axis].set_linewidth(1.1)

ax.set_ylim(0,frq[:,1:].max()*1.1)
ax.set_xlim(0,frq.shape[0])

#ax.set_xticks(np.linspace(-1,1,9))

ax.minorticks_on()
ax.tick_params(which='both', width=1, labelsize='x-large')
ax.tick_params(which='major', length=5)
ax.tick_params(which='minor', length=3, color='k')

ax.set_ylabel('ThZ',labelpad=-2.0,fontweight='normal',fontsize='x-large')
#ax.set_xlabel('x',labelpad=1.0,fontweight='normal',fontsize='x-large')


#fig.suptitle('matplotlib example',y=0.97,fontsize='x-large')
#plt.savefig('example.png',format='png',dpi=300,bbox_inches='tight')

plt.show()

